/**
 * Public API report for the frozen TypeScript SDK packages (Phase 4 item 5, WS5).
 *
 * @acp/agent-sdk, @acp/tool-client, and @acp/llm-client are part of the 1.0
 * SemVer surface (docs/standards/api-versioning.md). This tool extracts the
 * exported declaration surface from each package's built dist/index.d.ts and
 * writes a committed report to <pkg>/etc/<pkg>.api.md. CI regenerates and
 * diffs it (like the `contracts` gate): an undocumented change to the export
 * surface fails the build, so a breaking or accidental API change can never
 * land silently.
 *
 * Uses the TypeScript compiler API (already a root devDependency) rather than
 * an extra tool — the report is the resolved declaration text, deterministic
 * and path-independent.
 *
 * Usage: node scripts/api-report.mjs           # regenerate every report
 *        node scripts/api-report.mjs --check    # fail (exit 1) if any report is stale
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, join, resolve, basename } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const ts = require('typescript');

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');

const PACKAGES = [
  ['@acp/agent-sdk', 'packages/agent-sdk'],
  ['@acp/tool-client', 'packages/tool-client'],
  ['@acp/llm-client', 'packages/llm-client'],
];

function reportFor(pkgName, pkgDir) {
  const entry = join(REPO_ROOT, pkgDir, 'dist', 'index.d.ts');
  if (!existsSync(entry)) {
    throw new Error(`${pkgName}: ${entry} not found — run \`pnpm build\` first`);
  }
  const program = ts.createProgram([entry], {
    target: ts.ScriptTarget.ES2022,
    module: ts.ModuleKind.NodeNext,
    moduleResolution: ts.ModuleResolutionKind.NodeNext,
    noEmit: true,
    skipLibCheck: true,
  });
  const checker = program.getTypeChecker();
  const source = program.getSourceFile(entry);
  const moduleSymbol = checker.getSymbolAtLocation(source);
  if (!moduleSymbol) throw new Error(`${pkgName}: could not resolve module symbol`);

  const printer = ts.createPrinter({ removeComments: true, newLine: ts.NewLineKind.LineFeed });
  const lines = [];
  const exports = checker.getExportsOfModule(moduleSymbol);
  for (const sym of exports) {
    const resolved = sym.flags & ts.SymbolFlags.Alias ? checker.getAliasedSymbol(sym) : sym;
    const decl = resolved.declarations?.[0];
    if (!decl) continue;
    let text;
    if (
      ts.isInterfaceDeclaration(decl) ||
      ts.isTypeAliasDeclaration(decl) ||
      ts.isEnumDeclaration(decl) ||
      ts.isClassDeclaration(decl) ||
      ts.isFunctionDeclaration(decl)
    ) {
      // Print the resolved declaration; classes/functions keep only their
      // signature surface (drop bodies for a stable, readable report).
      const printable = printSignature(decl);
      text = printer.printNode(ts.EmitHint.Unspecified, printable, decl.getSourceFile());
    } else {
      // const/let/var and anything else: name + resolved type string.
      const type = checker.getTypeOfSymbolAtLocation(resolved, decl);
      text = `const ${sym.getName()}: ${checker.typeToString(type, decl, ts.TypeFormatFlags.NoTruncation)};`;
    }
    lines.push({ name: sym.getName(), text: text.trim() });
  }
  lines.sort((a, b) => a.name.localeCompare(b.name));
  const body = lines.map((l) => l.text).join('\n\n');
  return (
    `<!-- Generated by scripts/api-report.mjs — DO NOT EDIT. Run \`pnpm api:report\`. -->\n\n` +
    `# ${pkgName} public API\n\n` +
    `The frozen 1.0 export surface (docs/standards/api-versioning.md). A diff here\n` +
    `is an API change: additive in a minor, breaking only in a major.\n\n` +
    '```ts\n' +
    `${body}\n` +
    '```\n'
  );
}

// Strip class/function bodies so the report is a signature surface, not an impl.
function printSignature(decl) {
  if (ts.isFunctionDeclaration(decl)) {
    return ts.factory.updateFunctionDeclaration(
      decl,
      decl.modifiers?.filter((m) => m.kind !== ts.SyntaxKind.DeclareKeyword),
      decl.asteriskToken,
      decl.name,
      decl.typeParameters,
      decl.parameters,
      decl.type,
      undefined,
    );
  }
  if (ts.isClassDeclaration(decl)) {
    const members = decl.members.filter(
      (m) =>
        !ts.isPropertyDeclaration(m) ||
        !m.modifiers?.some((x) => x.kind === ts.SyntaxKind.PrivateKeyword),
    );
    return ts.factory.updateClassDeclaration(
      decl,
      decl.modifiers?.filter((m) => m.kind !== ts.SyntaxKind.DeclareKeyword),
      decl.name,
      decl.typeParameters,
      decl.heritageClauses,
      members.map((m) => {
        if (ts.isMethodDeclaration(m)) {
          return ts.factory.updateMethodDeclaration(
            m,
            m.modifiers,
            m.asteriskToken,
            m.name,
            m.questionToken,
            m.typeParameters,
            m.parameters,
            m.type,
            undefined,
          );
        }
        if (ts.isConstructorDeclaration(m)) {
          return ts.factory.updateConstructorDeclaration(m, m.modifiers, m.parameters, undefined);
        }
        return m;
      }),
    );
  }
  return decl;
}

function main() {
  const check = process.argv.includes('--check');
  let stale = false;
  for (const [pkgName, pkgDir] of PACKAGES) {
    const report = reportFor(pkgName, pkgDir);
    const etcDir = join(REPO_ROOT, pkgDir, 'etc');
    const outPath = join(etcDir, `${basename(pkgDir)}.api.md`);
    if (check) {
      const existing = existsSync(outPath) ? readFileSync(outPath, 'utf8') : '';
      if (existing !== report) {
        stale = true;
        process.stderr.write(
          `api-report: ${outPath} is stale — run \`pnpm api:report\` and commit.\n`,
        );
      }
    } else {
      mkdirSync(etcDir, { recursive: true });
      writeFileSync(outPath, report);
      process.stdout.write(`api-report: wrote ${outPath}\n`);
    }
  }
  return stale ? 1 : 0;
}

process.exit(main());
